name: Quality checks

on: [push, pull_request]

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lint-command:
          - npm run lint:md
          - npm run lint:relative-urls
          - npm run lint:external-urls
          - npm run lint:consistency
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
      - name: Install dependencies
        run: npm ci
      - name: Ensure consistency
        run: ${{ matrix.lint-command }}